/**
 * Levolor Order Specifications — MIRRORS THE DEALER PORTAL EXACTLY
 *
 * Each product has a set of required fields that must be filled in
 * to generate a valid manufacturer order. These fields map 1:1 to
 * the Levolor dealer portal entry screens.
 *
 * AI AGENT PROCESSING:
 * The completed order form from a customer produces a JSON payload
 * that can be entered directly into Levolor's dealer portal by an
 * AI agent — no human translation needed.
 */

import type { OrderField } from './norman-order-specs';

// ============================================================
// 1. LEVOLOR 9/16" CELLULAR SHADES
// ============================================================

export const LEVOLOR_CELLULAR_ORDER_FIELDS: OrderField[] = [
  {
    id: 'cellSize',
    label: 'Cell Size',
    portalLabel: 'Cell Size',
    type: 'select',
    required: true,
    priority: 'essential',
    portalSection: 'Product',
    options: [
      { value: '9_16_single', label: '9/16" Single Cell', portalValue: '9/16" Single Cell' },
      { value: '9_16_double', label: '9/16" Double Cell', portalValue: '9/16" Double Cell' },
    ],
    helpText: 'Single cell is standard. Double cell provides extra insulation.',
  },
  {
    id: 'opacity',
    label: 'Light Control',
    portalLabel: 'Opacity',
    type: 'select',
    required: true,
    priority: 'essential',
    portalSection: 'Fabric',
    options: [
      { value: 'light_filtering', label: 'Light Filtering — Softens light, maintains privacy', portalValue: 'Light Filtering' },
      { value: 'room_darkening', label: 'Room Darkening — Blocks most light', portalValue: 'Room Darkening' },
      { value: 'blackout', label: 'Blackout — Maximum light blockage', portalValue: 'Blackout' },
    ],
    helpText: 'Bedrooms and nurseries benefit from Room Darkening or Blackout.',
  },
  {
    id: 'fabricColor',
    label: 'Color',
    portalLabel: 'Fabric Color',
    type: 'color',
    required: true,
    priority: 'essential',
    portalSection: 'Fabric',
    helpText: 'Select from available Levolor cellular fabric colors',
  },
  {
    id: 'liftSystem',
    label: 'Lift System',
    portalLabel: 'Lift System',
    type: 'select',
    required: true,
    priority: 'essential',
    portalSection: 'Options',
    options: [
      { value: 'cordless', label: 'Cordless — Push up/pull down', portalValue: 'Cordless' },
      { value: 'top_down_bottom_up', label: 'Top-Down/Bottom-Up — Adjustable from both ends', portalValue: 'Top-Down/Bottom-Up', surcharge: 50, surchargeType: 'flat' },
      { value: 'motorized', label: 'Motorized — Remote or app controlled', portalValue: 'Motorized', surcharge: 200, surchargeType: 'flat' },
    ],
    helpText: 'Cordless is safest for kids and pets. Top-Down/Bottom-Up allows privacy with natural light from above.',
  },
  {
    id: 'mountType',
    label: 'Mount Type',
    portalLabel: 'Mount Type',
    type: 'select',
    required: true,
    priority: 'essential',
    portalSection: 'Measurements',
    options: [
      { value: 'inside', label: 'Inside Mount — Fits inside the window frame', portalValue: 'Inside Mount' },
      { value: 'outside', label: 'Outside Mount — Mounts on wall above window', portalValue: 'Outside Mount' },
    ],
    helpText: 'Inside mount looks cleaner. Outside mount provides better light blockage.',
  },
  {
    id: 'width',
    label: 'Width',
    portalLabel: 'Width',
    type: 'number',
    required: true,
    priority: 'essential',
    min: 18,
    max: 96,
    step: 0.125,
    portalSection: 'Measurements',
    helpText: 'Measure to the nearest 1/8". Use the narrowest measurement for inside mount.',
  },
  {
    id: 'height',
    label: 'Height',
    portalLabel: 'Height',
    type: 'number',
    required: true,
    priority: 'essential',
    min: 18,
    max: 96,
    step: 0.125,
    portalSection: 'Measurements',
    helpText: 'Measure to the nearest 1/8". Use the shortest measurement for inside mount.',
  },
  {
    id: 'controlSide',
    label: 'Control Side',
    portalLabel: 'Control Position',
    type: 'select',
    required: true,
    priority: 'essential',
    portalSection: 'Options',
    options: [
      { value: 'right', label: 'Right (standard)', portalValue: 'Right' },
      { value: 'left', label: 'Left', portalValue: 'Left' },
    ],
    default: 'right',
    dependsOn: { field: 'liftSystem', value: ['motorized'] },
    helpText: 'Which side to place the motor receiver for remote pairing.',
  },
  {
    id: 'headrailColor',
    label: 'Headrail Color',
    portalLabel: 'Headrail Color',
    type: 'select',
    required: true,
    priority: 'optional',
    portalSection: 'Options',
    options: [
      { value: 'matching', label: 'Match Fabric (standard)', portalValue: 'Matching' },
      { value: 'white', label: 'White', portalValue: 'White' },
    ],
    default: 'matching',
  },
  {
    id: 'bottomRail',
    label: 'Bottom Rail',
    portalLabel: 'Bottom Rail Style',
    type: 'select',
    required: false,
    priority: 'optional',
    portalSection: 'Options',
    options: [
      { value: 'standard', label: 'Standard', portalValue: 'Standard' },
      { value: 'contoured', label: 'Contoured', portalValue: 'Contoured' },
    ],
    default: 'standard',
    helpText: 'Contoured rail creates a finished look at the bottom of the shade.',
  },
];

// ============================================================
// 2. LEVOLOR ROLLER SHADES
// ============================================================

export const LEVOLOR_ROLLER_ORDER_FIELDS: OrderField[] = [
  {
    id: 'opacity',
    label: 'Light Control',
    portalLabel: 'Opacity',
    type: 'select',
    required: true,
    priority: 'essential',
    portalSection: 'Fabric',
    options: [
      { value: 'light_filtering', label: 'Light Filtering — Softens light, maintains privacy', portalValue: 'Light Filtering' },
      { value: 'room_darkening', label: 'Room Darkening — Blocks most light', portalValue: 'Room Darkening' },
      { value: 'solar_screen_5', label: 'Solar Screen (5%) — View-through UV protection', portalValue: 'Solar Screen 5%' },
    ],
    helpText: 'Solar Screen allows outward visibility while blocking UV rays and glare.',
  },
  {
    id: 'fabricColor',
    label: 'Color',
    portalLabel: 'Fabric Color',
    type: 'color',
    required: true,
    priority: 'essential',
    portalSection: 'Fabric',
    helpText: 'Select from available Levolor roller shade fabric colors',
  },
  {
    id: 'rollType',
    label: 'Roll Type',
    portalLabel: 'Roll Type',
    type: 'select',
    required: true,
    priority: 'essential',
    portalSection: 'Product',
    options: [
      { value: 'standard', label: 'Standard Roll — Fabric rolls behind the tube', portalValue: 'Standard Roll' },
      { value: 'reverse', label: 'Reverse Roll — Fabric rolls in front of the tube', portalValue: 'Reverse Roll' },
    ],
    helpText: 'Reverse roll positions the shade closer to the glass for better light gap coverage.',
  },
  {
    id: 'liftSystem',
    label: 'Lift System',
    portalLabel: 'Lift System',
    type: 'select',
    required: true,
    priority: 'essential',
    portalSection: 'Options',
    options: [
      { value: 'cordless_spring', label: 'Cordless Spring — Gentle pull to operate', portalValue: 'Cordless Spring' },
      { value: 'continuous_loop', label: 'Continuous Loop — Chain control', portalValue: 'Continuous Loop' },
      { value: 'motorized', label: 'Motorized — Remote or app controlled', portalValue: 'Motorized', surcharge: 200, surchargeType: 'flat' },
    ],
    helpText: 'Cordless spring is child-safe. Continuous loop is ideal for large or heavy shades.',
  },
  {
    id: 'controlSide',
    label: 'Control Side',
    portalLabel: 'Control Position',
    type: 'select',
    required: true,
    priority: 'essential',
    portalSection: 'Options',
    options: [
      { value: 'right', label: 'Right (standard)', portalValue: 'Right' },
      { value: 'left', label: 'Left', portalValue: 'Left' },
    ],
    default: 'right',
    dependsOn: { field: 'liftSystem', value: ['continuous_loop'] },
    helpText: 'Which side to place the chain loop control.',
  },
  {
    id: 'valanceType',
    label: 'Valance Type',
    portalLabel: 'Valance',
    type: 'select',
    required: true,
    priority: 'essential',
    portalSection: 'Options',
    options: [
      { value: 'open_roll', label: 'Open Roll — No valance, exposed roller', portalValue: 'Open Roll' },
      { value: 'cassette', label: 'Cassette — Enclosed headrail cover', portalValue: 'Cassette', surcharge: 30, surchargeType: 'flat' },
    ],
    helpText: 'Cassette provides a clean, finished look and protects the fabric when raised.',
  },
  {
    id: 'mountType',
    label: 'Mount Type',
    portalLabel: 'Mount Type',
    type: 'select',
    required: true,
    priority: 'essential',
    portalSection: 'Measurements',
    options: [
      { value: 'inside', label: 'Inside Mount — Fits inside the window frame', portalValue: 'Inside Mount' },
      { value: 'outside', label: 'Outside Mount — Mounts on wall above window', portalValue: 'Outside Mount' },
      { value: 'ceiling', label: 'Ceiling Mount — Mounts to ceiling or soffit', portalValue: 'Ceiling Mount' },
    ],
    helpText: 'Ceiling mount is ideal for floor-to-ceiling windows or rooms without trim.',
  },
  {
    id: 'width',
    label: 'Width',
    portalLabel: 'Width',
    type: 'number',
    required: true,
    priority: 'essential',
    min: 18,
    max: 96,
    step: 0.125,
    portalSection: 'Measurements',
    helpText: 'Measure to the nearest 1/8". Use the narrowest measurement for inside mount.',
  },
  {
    id: 'height',
    label: 'Height',
    portalLabel: 'Height',
    type: 'number',
    required: true,
    priority: 'essential',
    min: 18,
    max: 96,
    step: 0.125,
    portalSection: 'Measurements',
    helpText: 'Measure to the nearest 1/8". Use the shortest measurement for inside mount.',
  },
];

// ============================================================
// 3. LEVOLOR ROMAN SHADES
// ============================================================

export const LEVOLOR_ROMAN_ORDER_FIELDS: OrderField[] = [
  {
    id: 'foldStyle',
    label: 'Fold Style',
    portalLabel: 'Fold Style',
    type: 'select',
    required: true,
    priority: 'essential',
    portalSection: 'Product',
    options: [
      { value: 'flat_fold', label: 'Flat Fold — Clean, modern stacking', portalValue: 'Flat Fold' },
      { value: 'hobbled', label: 'Hobbled/Waterfall — Soft, cascading folds', portalValue: 'Hobbled/Waterfall' },
    ],
    helpText: 'Flat fold for a modern look. Hobbled for a traditional, layered appearance.',
  },
  {
    id: 'opacity',
    label: 'Light Control',
    portalLabel: 'Opacity',
    type: 'select',
    required: true,
    priority: 'essential',
    portalSection: 'Fabric',
    options: [
      { value: 'light_filtering', label: 'Light Filtering — Softens light, maintains privacy', portalValue: 'Light Filtering' },
      { value: 'room_darkening', label: 'Room Darkening — Blocks most light', portalValue: 'Room Darkening' },
    ],
  },
  {
    id: 'fabricColor',
    label: 'Color',
    portalLabel: 'Fabric Color',
    type: 'color',
    required: true,
    priority: 'essential',
    portalSection: 'Fabric',
    helpText: 'Select from available Levolor roman shade fabric colors',
  },
  {
    id: 'liftSystem',
    label: 'Lift System',
    portalLabel: 'Lift System',
    type: 'select',
    required: true,
    priority: 'essential',
    portalSection: 'Options',
    options: [
      { value: 'cordless', label: 'Cordless — Push up/pull down', portalValue: 'Cordless' },
      { value: 'continuous_loop', label: 'Continuous Loop — Chain control', portalValue: 'Continuous Loop' },
    ],
    helpText: 'Cordless is child-safe. Continuous loop recommended for heavier fabric options.',
  },
  {
    id: 'controlSide',
    label: 'Control Side',
    portalLabel: 'Control Position',
    type: 'select',
    required: true,
    priority: 'essential',
    portalSection: 'Options',
    options: [
      { value: 'right', label: 'Right (standard)', portalValue: 'Right' },
      { value: 'left', label: 'Left', portalValue: 'Left' },
    ],
    default: 'right',
    dependsOn: { field: 'liftSystem', value: ['continuous_loop'] },
    helpText: 'Which side to place the chain loop control.',
  },
  {
    id: 'lining',
    label: 'Lining',
    portalLabel: 'Lining',
    type: 'select',
    required: true,
    priority: 'optional',
    portalSection: 'Options',
    options: [
      { value: 'standard', label: 'Standard Lining', portalValue: 'Standard' },
      { value: 'blackout', label: 'Blackout Lining — Maximum light blockage', portalValue: 'Blackout Lining', surcharge: 20, surchargeType: 'percent' },
    ],
    default: 'standard',
    helpText: 'Add blackout lining for bedrooms or media rooms.',
  },
  {
    id: 'mountType',
    label: 'Mount Type',
    portalLabel: 'Mount Type',
    type: 'select',
    required: true,
    priority: 'essential',
    portalSection: 'Measurements',
    options: [
      { value: 'inside', label: 'Inside Mount — Fits inside the window frame', portalValue: 'Inside Mount' },
      { value: 'outside', label: 'Outside Mount — Mounts on wall above window', portalValue: 'Outside Mount' },
    ],
    helpText: 'Inside mount requires minimum 2" depth. Outside mount provides better light blockage.',
  },
  {
    id: 'width',
    label: 'Width',
    portalLabel: 'Width',
    type: 'number',
    required: true,
    priority: 'essential',
    min: 18,
    max: 72,
    step: 0.125,
    portalSection: 'Measurements',
    helpText: 'Measure to the nearest 1/8". Use the narrowest measurement for inside mount.',
  },
  {
    id: 'height',
    label: 'Height',
    portalLabel: 'Height',
    type: 'number',
    required: true,
    priority: 'essential',
    min: 18,
    max: 72,
    step: 0.125,
    portalSection: 'Measurements',
    helpText: 'Measure to the nearest 1/8". Use the shortest measurement for inside mount.',
  },
];

// ============================================================
// 4. LEVOLOR FAUX WOOD BLINDS
// ============================================================

export const LEVOLOR_FAUX_WOOD_ORDER_FIELDS: OrderField[] = [
  {
    id: 'slatSize',
    label: 'Slat Size',
    portalLabel: 'Slat Size',
    type: 'select',
    required: true,
    priority: 'essential',
    portalSection: 'Product',
    options: [
      { value: '2', label: '2"', portalValue: '2"' },
      { value: '2_1_2', label: '2-1/2"', portalValue: '2-1/2"' },
    ],
    helpText: '2" slats fit smaller windows. 2-1/2" slats provide a bolder look with better view-through.',
  },
  {
    id: 'finish',
    label: 'Finish',
    portalLabel: 'Finish',
    type: 'select',
    required: true,
    priority: 'essential',
    portalSection: 'Product',
    options: [
      { value: 'smooth', label: 'Smooth — Clean, painted look', portalValue: 'Smooth' },
      { value: 'woodgrain', label: 'Woodgrain — Realistic wood texture', portalValue: 'Woodgrain' },
    ],
    helpText: 'Woodgrain mimics real wood at a fraction of the cost.',
  },
  {
    id: 'color',
    label: 'Color',
    portalLabel: 'Color',
    type: 'color',
    required: true,
    priority: 'essential',
    portalSection: 'Product',
    helpText: 'Select from available Levolor faux wood finish colors',
  },
  {
    id: 'liftSystem',
    label: 'Lift System',
    portalLabel: 'Lift System',
    type: 'select',
    required: true,
    priority: 'essential',
    portalSection: 'Options',
    options: [
      { value: 'cordless', label: 'Cordless — Push up/pull down', portalValue: 'Cordless' },
      { value: 'standard_cord', label: 'Standard Cord — Traditional pull cord', portalValue: 'Standard Cord' },
    ],
    helpText: 'Cordless is safest for homes with children and pets.',
  },
  {
    id: 'tiltType',
    label: 'Tilt Type',
    portalLabel: 'Tilt Control',
    type: 'select',
    required: true,
    priority: 'essential',
    portalSection: 'Options',
    options: [
      { value: 'wand', label: 'Wand Tilt — Twist wand to angle slats', portalValue: 'Wand Tilt' },
      { value: 'cord', label: 'Cord Tilt — Pull cord to angle slats', portalValue: 'Cord Tilt' },
    ],
    helpText: 'Wand tilt is child-safe and easier to operate.',
  },
  {
    id: 'controlSide',
    label: 'Control Side',
    portalLabel: 'Control Position',
    type: 'select',
    required: true,
    priority: 'essential',
    portalSection: 'Options',
    options: [
      { value: 'right', label: 'Right (standard)', portalValue: 'Right' },
      { value: 'left', label: 'Left', portalValue: 'Left' },
    ],
    default: 'right',
    helpText: 'Which side to place the tilt wand or cord.',
  },
  {
    id: 'valance',
    label: 'Valance',
    portalLabel: 'Valance',
    type: 'select',
    required: true,
    priority: 'optional',
    portalSection: 'Options',
    options: [
      { value: '2_1_2_crown', label: '2-1/2" Crown Valance (standard)', portalValue: '2-1/2" Crown' },
      { value: 'no_valance', label: 'No Valance', portalValue: 'No Valance' },
    ],
    default: '2_1_2_crown',
    helpText: 'Crown valance covers the headrail for a finished look.',
  },
  {
    id: 'routeHoles',
    label: 'Route Holes',
    portalLabel: 'Route Holes',
    type: 'select',
    required: true,
    priority: 'optional',
    portalSection: 'Options',
    options: [
      { value: 'standard', label: 'Standard — Visible ladder cord holes', portalValue: 'Standard' },
      { value: 'routeless', label: 'Routeless — No visible holes for better privacy', portalValue: 'Routeless', surcharge: 10, surchargeType: 'percent' },
    ],
    default: 'standard',
    helpText: 'Routeless eliminates light dots when slats are closed for improved privacy.',
  },
  {
    id: 'mountType',
    label: 'Mount Type',
    portalLabel: 'Mount Type',
    type: 'select',
    required: true,
    priority: 'essential',
    portalSection: 'Measurements',
    options: [
      { value: 'inside', label: 'Inside Mount — Fits inside the window frame', portalValue: 'Inside Mount' },
      { value: 'outside', label: 'Outside Mount — Mounts on wall above window', portalValue: 'Outside Mount' },
    ],
    helpText: 'Inside mount requires minimum 2-1/2" depth for 2" blinds.',
  },
  {
    id: 'width',
    label: 'Width',
    portalLabel: 'Width',
    type: 'number',
    required: true,
    priority: 'essential',
    min: 18,
    max: 72,
    step: 0.125,
    portalSection: 'Measurements',
    helpText: 'Measure to the nearest 1/8". Use the narrowest measurement for inside mount.',
  },
  {
    id: 'height',
    label: 'Height',
    portalLabel: 'Height',
    type: 'number',
    required: true,
    priority: 'essential',
    min: 18,
    max: 72,
    step: 0.125,
    portalSection: 'Measurements',
    helpText: 'Measure to the nearest 1/8". Use the shortest measurement for inside mount.',
  },
];

// ============================================================
// 5. LEVOLOR REAL WOOD BLINDS
// ============================================================

export const LEVOLOR_REAL_WOOD_ORDER_FIELDS: OrderField[] = [
  {
    id: 'slatSize',
    label: 'Slat Size',
    portalLabel: 'Slat Size',
    type: 'select',
    required: true,
    priority: 'essential',
    portalSection: 'Product',
    options: [
      { value: '2', label: '2"', portalValue: '2"' },
      { value: '2_1_2', label: '2-1/2"', portalValue: '2-1/2"' },
    ],
    helpText: '2" slats are classic. 2-1/2" slats offer a more contemporary look.',
  },
  {
    id: 'woodType',
    label: 'Wood Type',
    portalLabel: 'Wood Type',
    type: 'select',
    required: true,
    priority: 'essential',
    portalSection: 'Product',
    options: [
      { value: 'basswood', label: 'Basswood — Lightweight, durable hardwood', portalValue: 'Basswood' },
    ],
    helpText: 'Basswood is a premium, lightweight hardwood ideal for window blinds.',
  },
  {
    id: 'finishType',
    label: 'Finish Type',
    portalLabel: 'Finish Type',
    type: 'select',
    required: true,
    priority: 'essential',
    portalSection: 'Product',
    options: [
      { value: 'painted', label: 'Painted — Solid color finish', portalValue: 'Painted' },
      { value: 'stained', label: 'Stained — Natural wood grain visible', portalValue: 'Stained' },
    ],
    helpText: 'Stained finishes showcase the natural beauty of the wood grain.',
  },
  {
    id: 'color',
    label: 'Color',
    portalLabel: 'Color',
    type: 'color',
    required: true,
    priority: 'essential',
    portalSection: 'Product',
    helpText: 'Select from available Levolor real wood finish colors and stains',
  },
  {
    id: 'liftSystem',
    label: 'Lift System',
    portalLabel: 'Lift System',
    type: 'select',
    required: true,
    priority: 'essential',
    portalSection: 'Options',
    options: [
      { value: 'cordless', label: 'Cordless — Push up/pull down', portalValue: 'Cordless' },
      { value: 'standard_cord', label: 'Standard Cord — Traditional pull cord', portalValue: 'Standard Cord' },
    ],
    helpText: 'Cordless is safest for homes with children and pets.',
  },
  {
    id: 'tiltType',
    label: 'Tilt Type',
    portalLabel: 'Tilt Control',
    type: 'select',
    required: true,
    priority: 'essential',
    portalSection: 'Options',
    options: [
      { value: 'wand', label: 'Wand Tilt — Twist wand to angle slats', portalValue: 'Wand Tilt' },
      { value: 'cord', label: 'Cord Tilt — Pull cord to angle slats', portalValue: 'Cord Tilt' },
    ],
    helpText: 'Wand tilt is child-safe and easier to operate.',
  },
  {
    id: 'controlSide',
    label: 'Control Side',
    portalLabel: 'Control Position',
    type: 'select',
    required: true,
    priority: 'essential',
    portalSection: 'Options',
    options: [
      { value: 'right', label: 'Right (standard)', portalValue: 'Right' },
      { value: 'left', label: 'Left', portalValue: 'Left' },
    ],
    default: 'right',
    helpText: 'Which side to place the tilt wand or cord.',
  },
  {
    id: 'valance',
    label: 'Valance',
    portalLabel: 'Valance',
    type: 'select',
    required: true,
    priority: 'optional',
    portalSection: 'Options',
    options: [
      { value: '2_1_2_crown', label: '2-1/2" Crown Valance (standard)', portalValue: '2-1/2" Crown' },
      { value: 'no_valance', label: 'No Valance', portalValue: 'No Valance' },
    ],
    default: '2_1_2_crown',
    helpText: 'Crown valance covers the headrail for a finished look.',
  },
  {
    id: 'routeHoles',
    label: 'Route Holes',
    portalLabel: 'Route Holes',
    type: 'select',
    required: true,
    priority: 'optional',
    portalSection: 'Options',
    options: [
      { value: 'standard', label: 'Standard — Visible ladder cord holes', portalValue: 'Standard' },
      { value: 'routeless', label: 'Routeless — No visible holes for better privacy', portalValue: 'Routeless', surcharge: 10, surchargeType: 'percent' },
    ],
    default: 'standard',
    helpText: 'Routeless eliminates light dots when slats are closed for improved privacy.',
  },
  {
    id: 'mountType',
    label: 'Mount Type',
    portalLabel: 'Mount Type',
    type: 'select',
    required: true,
    priority: 'essential',
    portalSection: 'Measurements',
    options: [
      { value: 'inside', label: 'Inside Mount — Fits inside the window frame', portalValue: 'Inside Mount' },
      { value: 'outside', label: 'Outside Mount — Mounts on wall above window', portalValue: 'Outside Mount' },
    ],
    helpText: 'Inside mount requires minimum 2-3/4" depth for 2" blinds.',
  },
  {
    id: 'width',
    label: 'Width',
    portalLabel: 'Width',
    type: 'number',
    required: true,
    priority: 'essential',
    min: 18,
    max: 72,
    step: 0.125,
    portalSection: 'Measurements',
    helpText: 'Measure to the nearest 1/8". Use the narrowest measurement for inside mount.',
  },
  {
    id: 'height',
    label: 'Height',
    portalLabel: 'Height',
    type: 'number',
    required: true,
    priority: 'essential',
    min: 18,
    max: 72,
    step: 0.125,
    portalSection: 'Measurements',
    helpText: 'Measure to the nearest 1/8". Use the shortest measurement for inside mount.',
  },
];

// ============================================================
// 6. LEVOLOR RIVIERA METAL BLINDS
// ============================================================

export const LEVOLOR_RIVIERA_METAL_ORDER_FIELDS: OrderField[] = [
  {
    id: 'slatSize',
    label: 'Slat Size',
    portalLabel: 'Slat Size',
    type: 'select',
    required: true,
    priority: 'essential',
    portalSection: 'Product',
    options: [
      { value: '1_mini', label: '1" Mini — Classic mini blind', portalValue: '1" Mini' },
      { value: '1_2_micro', label: '1/2" Micro — Sleek, narrow profile', portalValue: '1/2" Micro' },
    ],
    helpText: '1" mini is the most popular. 1/2" micro provides a sleeker, more modern look.',
  },
  {
    id: 'color',
    label: 'Color',
    portalLabel: 'Color',
    type: 'color',
    required: true,
    priority: 'essential',
    portalSection: 'Product',
    helpText: 'Select from available Levolor Riviera metal blind colors',
  },
  {
    id: 'liftSystem',
    label: 'Lift System',
    portalLabel: 'Lift System',
    type: 'select',
    required: true,
    priority: 'essential',
    portalSection: 'Options',
    options: [
      { value: 'cordless', label: 'Cordless — Push up/pull down', portalValue: 'Cordless' },
      { value: 'standard_cord', label: 'Standard Cord — Traditional pull cord', portalValue: 'Standard Cord' },
    ],
    helpText: 'Cordless is safest for homes with children and pets.',
  },
  {
    id: 'tiltType',
    label: 'Tilt Type',
    portalLabel: 'Tilt Control',
    type: 'select',
    required: true,
    priority: 'essential',
    portalSection: 'Options',
    options: [
      { value: 'wand', label: 'Wand Tilt — Twist wand to angle slats', portalValue: 'Wand Tilt' },
    ],
    helpText: 'Wand tilt provides easy, child-safe slat angle control.',
  },
  {
    id: 'controlSide',
    label: 'Control Side',
    portalLabel: 'Control Position',
    type: 'select',
    required: true,
    priority: 'essential',
    portalSection: 'Options',
    options: [
      { value: 'right', label: 'Right (standard)', portalValue: 'Right' },
      { value: 'left', label: 'Left', portalValue: 'Left' },
    ],
    default: 'right',
    helpText: 'Which side to place the tilt wand.',
  },
  {
    id: 'valance',
    label: 'Valance',
    portalLabel: 'Valance',
    type: 'select',
    required: true,
    priority: 'optional',
    portalSection: 'Options',
    options: [
      { value: 'standard', label: 'Standard Valance (included)', portalValue: 'Standard Valance' },
      { value: 'no_valance', label: 'No Valance', portalValue: 'No Valance' },
    ],
    default: 'standard',
    helpText: 'Standard valance covers the headrail for a clean look.',
  },
  {
    id: 'mountType',
    label: 'Mount Type',
    portalLabel: 'Mount Type',
    type: 'select',
    required: true,
    priority: 'essential',
    portalSection: 'Measurements',
    options: [
      { value: 'inside', label: 'Inside Mount — Fits inside the window frame', portalValue: 'Inside Mount' },
      { value: 'outside', label: 'Outside Mount — Mounts on wall above window', portalValue: 'Outside Mount' },
    ],
    helpText: 'Inside mount provides a clean, built-in appearance.',
  },
  {
    id: 'width',
    label: 'Width',
    portalLabel: 'Width',
    type: 'number',
    required: true,
    priority: 'essential',
    min: 18,
    max: 72,
    step: 0.125,
    portalSection: 'Measurements',
    helpText: 'Measure to the nearest 1/8". Use the narrowest measurement for inside mount.',
  },
  {
    id: 'height',
    label: 'Height',
    portalLabel: 'Height',
    type: 'number',
    required: true,
    priority: 'essential',
    min: 18,
    max: 72,
    step: 0.125,
    portalSection: 'Measurements',
    helpText: 'Measure to the nearest 1/8". Use the shortest measurement for inside mount.',
  },
];

// ============================================================
// 7. LEVOLOR BANDED/ZEBRA SHADES
// ============================================================

export const LEVOLOR_BANDED_ORDER_FIELDS: OrderField[] = [
  {
    id: 'opacity',
    label: 'Light Control',
    portalLabel: 'Opacity',
    type: 'select',
    required: true,
    priority: 'essential',
    portalSection: 'Fabric',
    options: [
      { value: 'light_filtering', label: 'Light Filtering — Alternating sheer and solid bands', portalValue: 'Light Filtering' },
      { value: 'room_darkening', label: 'Room Darkening — Opaque bands for maximum privacy', portalValue: 'Room Darkening' },
    ],
    helpText: 'Align the bands for view-through or overlap them for privacy.',
  },
  {
    id: 'fabricColor',
    label: 'Color',
    portalLabel: 'Fabric Color',
    type: 'color',
    required: true,
    priority: 'essential',
    portalSection: 'Fabric',
    helpText: 'Select from available Levolor banded shade fabric colors',
  },
  {
    id: 'liftSystem',
    label: 'Lift System',
    portalLabel: 'Lift System',
    type: 'select',
    required: true,
    priority: 'essential',
    portalSection: 'Options',
    options: [
      { value: 'cordless', label: 'Cordless — Push up/pull down', portalValue: 'Cordless' },
    ],
    helpText: 'Banded shades feature a cordless lift system for child and pet safety.',
  },
  {
    id: 'mountType',
    label: 'Mount Type',
    portalLabel: 'Mount Type',
    type: 'select',
    required: true,
    priority: 'essential',
    portalSection: 'Measurements',
    options: [
      { value: 'inside', label: 'Inside Mount — Fits inside the window frame', portalValue: 'Inside Mount' },
      { value: 'outside', label: 'Outside Mount — Mounts on wall above window', portalValue: 'Outside Mount' },
    ],
    helpText: 'Inside mount for a clean look. Outside mount for better light coverage.',
  },
  {
    id: 'width',
    label: 'Width',
    portalLabel: 'Width',
    type: 'number',
    required: true,
    priority: 'essential',
    min: 18,
    max: 72,
    step: 0.125,
    portalSection: 'Measurements',
    helpText: 'Measure to the nearest 1/8". Use the narrowest measurement for inside mount.',
  },
  {
    id: 'height',
    label: 'Height',
    portalLabel: 'Height',
    type: 'number',
    required: true,
    priority: 'essential',
    min: 18,
    max: 72,
    step: 0.125,
    portalSection: 'Measurements',
    helpText: 'Measure to the nearest 1/8". Use the shortest measurement for inside mount.',
  },
];

// ============================================================
// 8. LEVOLOR SOFT VERTICAL BLINDS
// ============================================================

export const LEVOLOR_SOFT_VERTICAL_ORDER_FIELDS: OrderField[] = [
  {
    id: 'opacity',
    label: 'Light Control',
    portalLabel: 'Opacity',
    type: 'select',
    required: true,
    priority: 'essential',
    portalSection: 'Fabric',
    options: [
      { value: 'light_filtering', label: 'Light Filtering — Softens light, maintains privacy', portalValue: 'Light Filtering' },
      { value: 'room_darkening', label: 'Room Darkening — Blocks most light', portalValue: 'Room Darkening' },
    ],
    helpText: 'Light filtering for living areas. Room darkening for bedrooms and media rooms.',
  },
  {
    id: 'fabricColor',
    label: 'Color',
    portalLabel: 'Fabric Color',
    type: 'color',
    required: true,
    priority: 'essential',
    portalSection: 'Fabric',
    helpText: 'Select from available Levolor soft vertical fabric colors',
  },
  {
    id: 'vaneSize',
    label: 'Vane Size',
    portalLabel: 'Vane Size',
    type: 'select',
    required: true,
    priority: 'essential',
    portalSection: 'Product',
    options: [
      { value: '3_1_2', label: '3-1/2"', portalValue: '3-1/2"' },
    ],
    helpText: 'Standard 3-1/2" vane width for soft vertical blinds.',
  },
  {
    id: 'controlSide',
    label: 'Control Side',
    portalLabel: 'Control Position',
    type: 'select',
    required: true,
    priority: 'essential',
    portalSection: 'Options',
    displayHint: 'image-card',
    options: [
      { value: 'right', label: 'Right — Control wand on right side', portalValue: 'Right' },
      { value: 'left', label: 'Left — Control wand on left side', portalValue: 'Left' },
    ],
    default: 'right',
    helpText: 'Choose which side is most accessible for opening and closing.',
  },
  {
    id: 'vaneStackLocation',
    label: 'Vane Stack Location',
    portalLabel: 'Stack Position',
    type: 'select',
    required: true,
    priority: 'essential',
    portalSection: 'Options',
    displayHint: 'image-card',
    options: [
      { value: 'left', label: 'Stack Left — Vanes gather to the left', portalValue: 'Stack Left' },
      { value: 'right', label: 'Stack Right — Vanes gather to the right', portalValue: 'Stack Right' },
      { value: 'split', label: 'Split Stack — Vanes open from center', portalValue: 'Split Stack' },
    ],
    helpText: 'Choose where the vanes stack when fully open. Split stack opens from the center like curtains.',
  },
  {
    id: 'mountType',
    label: 'Mount Type',
    portalLabel: 'Mount Type',
    type: 'select',
    required: true,
    priority: 'essential',
    portalSection: 'Measurements',
    options: [
      { value: 'inside', label: 'Inside Mount — Fits inside the window frame', portalValue: 'Inside Mount' },
      { value: 'outside', label: 'Outside Mount — Mounts on wall above window', portalValue: 'Outside Mount' },
    ],
    helpText: 'Outside mount is most common for sliding glass doors and wide openings.',
  },
  {
    id: 'width',
    label: 'Width',
    portalLabel: 'Width',
    type: 'number',
    required: true,
    priority: 'essential',
    min: 48,
    max: 192,
    step: 0.125,
    portalSection: 'Measurements',
    helpText: 'Measure the full width of the opening. For outside mount, add 3-4" on each side.',
  },
  {
    id: 'height',
    label: 'Height',
    portalLabel: 'Height',
    type: 'number',
    required: true,
    priority: 'essential',
    min: 48,
    max: 120,
    step: 0.125,
    portalSection: 'Measurements',
    helpText: 'Measure from top of opening to floor. Subtract 1/2" for clearance.',
  },
];
